LIBS += ../bayes/bayes.cpp
LIBS += ../bpnn/bpnn.cpp
LIBS += ../logistics/logistics.cpp
LIBS += ../perceptron/perceptron.cpp
LIBS += ../svm/svm.cpp
all:
	g++ -o test_xor test_xor.cpp $(LIBS)
	g++ -o number_classify number_classify.cpp $(LIBS)
	g++ -o test_bayes test_bayes.cpp $(LIBS)
